// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: receive/dbHandler.proto

package Database

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseLink_SendToDatabase_FullMethodName = "/dbHandler.DatabaseLink/SendToDatabase"
	DatabaseLink_Cancel_FullMethodName         = "/dbHandler.DatabaseLink/Cancel"
	DatabaseLink_CheckNode_FullMethodName      = "/dbHandler.DatabaseLink/CheckNode"
)

// DatabaseLinkClient is the client API for DatabaseLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseLinkClient interface {
	SendToDatabase(ctx context.Context, in *DatabaseConfig, opts ...grpc.CallOption) (*Response, error)
	Cancel(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error)
	CheckNode(ctx context.Context, in *CheckNodeRequest, opts ...grpc.CallOption) (*CheckNodeReply, error)
}

type databaseLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseLinkClient(cc grpc.ClientConnInterface) DatabaseLinkClient {
	return &databaseLinkClient{cc}
}

func (c *databaseLinkClient) SendToDatabase(ctx context.Context, in *DatabaseConfig, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DatabaseLink_SendToDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseLinkClient) Cancel(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, DatabaseLink_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseLinkClient) CheckNode(ctx context.Context, in *CheckNodeRequest, opts ...grpc.CallOption) (*CheckNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNodeReply)
	err := c.cc.Invoke(ctx, DatabaseLink_CheckNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseLinkServer is the server API for DatabaseLink service.
// All implementations must embed UnimplementedDatabaseLinkServer
// for forward compatibility.
type DatabaseLinkServer interface {
	SendToDatabase(context.Context, *DatabaseConfig) (*Response, error)
	Cancel(context.Context, *CancelMessage) (*CancelResponse, error)
	CheckNode(context.Context, *CheckNodeRequest) (*CheckNodeReply, error)
	mustEmbedUnimplementedDatabaseLinkServer()
}

// UnimplementedDatabaseLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseLinkServer struct{}

func (UnimplementedDatabaseLinkServer) SendToDatabase(context.Context, *DatabaseConfig) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToDatabase not implemented")
}
func (UnimplementedDatabaseLinkServer) Cancel(context.Context, *CancelMessage) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedDatabaseLinkServer) CheckNode(context.Context, *CheckNodeRequest) (*CheckNodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNode not implemented")
}
func (UnimplementedDatabaseLinkServer) mustEmbedUnimplementedDatabaseLinkServer() {}
func (UnimplementedDatabaseLinkServer) testEmbeddedByValue()                      {}

// UnsafeDatabaseLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseLinkServer will
// result in compilation errors.
type UnsafeDatabaseLinkServer interface {
	mustEmbedUnimplementedDatabaseLinkServer()
}

func RegisterDatabaseLinkServer(s grpc.ServiceRegistrar, srv DatabaseLinkServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseLink_ServiceDesc, srv)
}

func _DatabaseLink_SendToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseLinkServer).SendToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseLink_SendToDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseLinkServer).SendToDatabase(ctx, req.(*DatabaseConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseLink_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseLinkServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseLink_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseLinkServer).Cancel(ctx, req.(*CancelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseLink_CheckNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseLinkServer).CheckNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseLink_CheckNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseLinkServer).CheckNode(ctx, req.(*CheckNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseLink_ServiceDesc is the grpc.ServiceDesc for DatabaseLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbHandler.DatabaseLink",
	HandlerType: (*DatabaseLinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToDatabase",
			Handler:    _DatabaseLink_SendToDatabase_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _DatabaseLink_Cancel_Handler,
		},
		{
			MethodName: "CheckNode",
			Handler:    _DatabaseLink_CheckNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receive/dbHandler.proto",
}
