// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: back/Database/dbHandler.proto

package Database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Criterias     []*DataCriteria        `protobuf:"bytes,3,rep,name=Criterias,proto3" json:"Criterias,omitempty"`
	TrainURL      string                 `protobuf:"bytes,4,opt,name=TrainURL,proto3" json:"TrainURL,omitempty"`
	DBType        string                 `protobuf:"bytes,5,opt,name=DBType,proto3" json:"DBType,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	RemoteLogURL  string                 `protobuf:"bytes,7,opt,name=RemoteLogURL,proto3" json:"RemoteLogURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_back_Database_dbHandler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_back_Database_dbHandler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_back_Database_dbHandler_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseConfig) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DatabaseConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseConfig) GetCriterias() []*DataCriteria {
	if x != nil {
		return x.Criterias
	}
	return nil
}

func (x *DatabaseConfig) GetTrainURL() string {
	if x != nil {
		return x.TrainURL
	}
	return ""
}

func (x *DatabaseConfig) GetDBType() string {
	if x != nil {
		return x.DBType
	}
	return ""
}

func (x *DatabaseConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseConfig) GetRemoteLogURL() string {
	if x != nil {
		return x.RemoteLogURL
	}
	return ""
}

type DataCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCriteria) Reset() {
	*x = DataCriteria{}
	mi := &file_back_Database_dbHandler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCriteria) ProtoMessage() {}

func (x *DataCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_back_Database_dbHandler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCriteria.ProtoReflect.Descriptor instead.
func (*DataCriteria) Descriptor() ([]byte, []int) {
	return file_back_Database_dbHandler_proto_rawDescGZIP(), []int{1}
}

func (x *DataCriteria) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DataCriteria) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *DataCriteria) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_back_Database_dbHandler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_back_Database_dbHandler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_back_Database_dbHandler_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMessage) Reset() {
	*x = CancelMessage{}
	mi := &file_back_Database_dbHandler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMessage) ProtoMessage() {}

func (x *CancelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_back_Database_dbHandler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMessage.ProtoReflect.Descriptor instead.
func (*CancelMessage) Descriptor() ([]byte, []int) {
	return file_back_Database_dbHandler_proto_rawDescGZIP(), []int{3}
}

func (x *CancelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_back_Database_dbHandler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_back_Database_dbHandler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_back_Database_dbHandler_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CancelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_back_Database_dbHandler_proto protoreflect.FileDescriptor

const file_back_Database_dbHandler_proto_rawDesc = "" +
	"\n" +
	"\x1dback/Database/dbHandler.proto\x12\tdbHandler\"\xe5\x01\n" +
	"\x0eDatabaseConfig\x12\x18\n" +
	"\aAccount\x18\x01 \x01(\tR\aAccount\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x125\n" +
	"\tCriterias\x18\x03 \x03(\v2\x17.dbHandler.DataCriteriaR\tCriterias\x12\x1a\n" +
	"\bTrainURL\x18\x04 \x01(\tR\bTrainURL\x12\x16\n" +
	"\x06DBType\x18\x05 \x01(\tR\x06DBType\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\x12\"\n" +
	"\fRemoteLogURL\x18\a \x01(\tR\fRemoteLogURL\"V\n" +
	"\fDataCriteria\x12\x14\n" +
	"\x05Field\x18\x01 \x01(\tR\x05Field\x12\x1a\n" +
	"\bOperator\x18\x02 \x01(\tR\bOperator\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\"4\n" +
	"\bResponse\x12\x12\n" +
	"\x04IsOk\x18\x01 \x01(\bR\x04IsOk\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"\x1f\n" +
	"\rCancelMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\":\n" +
	"\x0eCancelResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error2\x8f\x01\n" +
	"\fDatabaseLink\x12@\n" +
	"\x0eSendToDatabase\x12\x19.dbHandler.DatabaseConfig\x1a\x13.dbHandler.Response\x12=\n" +
	"\x06Cancel\x12\x18.dbHandler.CancelMessage\x1a\x19.dbHandler.CancelResponseB\x10Z\x0etrain/Databaseb\x06proto3"

var (
	file_back_Database_dbHandler_proto_rawDescOnce sync.Once
	file_back_Database_dbHandler_proto_rawDescData []byte
)

func file_back_Database_dbHandler_proto_rawDescGZIP() []byte {
	file_back_Database_dbHandler_proto_rawDescOnce.Do(func() {
		file_back_Database_dbHandler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_back_Database_dbHandler_proto_rawDesc), len(file_back_Database_dbHandler_proto_rawDesc)))
	})
	return file_back_Database_dbHandler_proto_rawDescData
}

var file_back_Database_dbHandler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_back_Database_dbHandler_proto_goTypes = []any{
	(*DatabaseConfig)(nil), // 0: dbHandler.DatabaseConfig
	(*DataCriteria)(nil),   // 1: dbHandler.DataCriteria
	(*Response)(nil),       // 2: dbHandler.Response
	(*CancelMessage)(nil),  // 3: dbHandler.CancelMessage
	(*CancelResponse)(nil), // 4: dbHandler.CancelResponse
}
var file_back_Database_dbHandler_proto_depIdxs = []int32{
	1, // 0: dbHandler.DatabaseConfig.Criterias:type_name -> dbHandler.DataCriteria
	0, // 1: dbHandler.DatabaseLink.SendToDatabase:input_type -> dbHandler.DatabaseConfig
	3, // 2: dbHandler.DatabaseLink.Cancel:input_type -> dbHandler.CancelMessage
	2, // 3: dbHandler.DatabaseLink.SendToDatabase:output_type -> dbHandler.Response
	4, // 4: dbHandler.DatabaseLink.Cancel:output_type -> dbHandler.CancelResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_back_Database_dbHandler_proto_init() }
func file_back_Database_dbHandler_proto_init() {
	if File_back_Database_dbHandler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_back_Database_dbHandler_proto_rawDesc), len(file_back_Database_dbHandler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_Database_dbHandler_proto_goTypes,
		DependencyIndexes: file_back_Database_dbHandler_proto_depIdxs,
		MessageInfos:      file_back_Database_dbHandler_proto_msgTypes,
	}.Build()
	File_back_Database_dbHandler_proto = out.File
	file_back_Database_dbHandler_proto_goTypes = nil
	file_back_Database_dbHandler_proto_depIdxs = nil
}
