// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cmd/cmdClient/client.proto

package cmdClient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMessage) Reset() {
	*x = ApplyMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMessage) ProtoMessage() {}

func (x *ApplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMessage.ProtoReflect.Descriptor instead.
func (*ApplyMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApplyMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ApplyResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMessage) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *TaskMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *TaskResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TaskResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CancelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMessage) Reset() {
	*x = CancelMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMessage) ProtoMessage() {}

func (x *CancelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMessage.ProtoReflect.Descriptor instead.
func (*CancelMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{4}
}

func (x *CancelMessage) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *CancelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CancelResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ExitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitMessage) Reset() {
	*x = ExitMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitMessage) ProtoMessage() {}

func (x *ExitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitMessage.ProtoReflect.Descriptor instead.
func (*ExitMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{6}
}

func (x *ExitMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitResponse) Reset() {
	*x = ExitResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitResponse) ProtoMessage() {}

func (x *ExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitResponse.ProtoReflect.Descriptor instead.
func (*ExitResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{7}
}

func (x *ExitResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ExitResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMessage) Reset() {
	*x = ViewMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMessage) ProtoMessage() {}

func (x *ViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMessage.ProtoReflect.Descriptor instead.
func (*ViewMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{8}
}

func (x *ViewMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ViewMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{9}
}

func (x *ViewResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ViewResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ViewResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *DeleteResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CheckNodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` //任务 id，为空表示所有任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNodeMessage) Reset() {
	*x = CheckNodeMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNodeMessage) ProtoMessage() {}

func (x *CheckNodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNodeMessage.ProtoReflect.Descriptor instead.
func (*CheckNodeMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{12}
}

func (x *CheckNodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Metrics       []*NodeMetrics         `protobuf:"bytes,3,rep,name=Metrics,proto3" json:"Metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNodeResponse) Reset() {
	*x = CheckNodeResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNodeResponse) ProtoMessage() {}

func (x *CheckNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNodeResponse.ProtoReflect.Descriptor instead.
func (*CheckNodeResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{13}
}

func (x *CheckNodeResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CheckNodeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CheckNodeResponse) GetMetrics() []*NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type NodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`     //该节点承载的所有任务 id（逗号分隔）
	Node          string                 `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"` //TRAIN / DATA
	Cpu           float32                `protobuf:"fixed32,3,opt,name=Cpu,proto3" json:"Cpu,omitempty"`
	Memory        float32                `protobuf:"fixed32,4,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Disk          float32                `protobuf:"fixed32,5,opt,name=Disk,proto3" json:"Disk,omitempty"`
	DiskIO        float32                `protobuf:"fixed32,6,opt,name=DiskIO,proto3" json:"DiskIO,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=Url,proto3" json:"Url,omitempty"` //节点地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{14}
}

func (x *NodeMetrics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeMetrics) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeMetrics) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *NodeMetrics) GetMemory() float32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *NodeMetrics) GetDisk() float32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *NodeMetrics) GetDiskIO() float32 {
	if x != nil {
		return x.DiskIO
	}
	return 0
}

func (x *NodeMetrics) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type JoinNodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=NodeType,proto3" json:"NodeType,omitempty"` //TRAIN / DATA
	Urls          []string               `protobuf:"bytes,2,rep,name=Urls,proto3" json:"Urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeMessage) Reset() {
	*x = JoinNodeMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeMessage) ProtoMessage() {}

func (x *JoinNodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeMessage.ProtoReflect.Descriptor instead.
func (*JoinNodeMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{15}
}

func (x *JoinNodeMessage) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *JoinNodeMessage) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type JoinNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeResponse) Reset() {
	*x = JoinNodeResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeResponse) ProtoMessage() {}

func (x *JoinNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeResponse.ProtoReflect.Descriptor instead.
func (*JoinNodeResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{16}
}

func (x *JoinNodeResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *JoinNodeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type DeleteNodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=Urls,proto3" json:"Urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeMessage) Reset() {
	*x = DeleteNodeMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeMessage) ProtoMessage() {}

func (x *DeleteNodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeMessage.ProtoReflect.Descriptor instead.
func (*DeleteNodeMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNodeMessage) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteNodeResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *DeleteNodeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_cmd_cmdClient_client_proto protoreflect.FileDescriptor

const file_cmd_cmdClient_client_proto_rawDesc = "" +
	"\n" +
	"\x1acmd/cmdClient/client.proto\x12\tcmdClient\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\fApplyMessage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\rApplyResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"C\n" +
	"\vTaskMessage\x12\x10\n" +
	"\x03All\x18\x01 \x01(\bR\x03All\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"P\n" +
	"\fTaskResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"E\n" +
	"\rCancelMessage\x12\x10\n" +
	"\x03All\x18\x01 \x01(\bR\x03All\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"@\n" +
	"\x0eCancelResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"!\n" +
	"\vExitMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\fExitResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"O\n" +
	"\vViewMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"P\n" +
	"\fViewResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"Q\n" +
	"\rDeleteMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"@\n" +
	"\x0eDeleteResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\"\n" +
	"\x10CheckNodeMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"u\n" +
	"\x11CheckNodeResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x120\n" +
	"\aMetrics\x18\x03 \x03(\v2\x16.cmdClient.NodeMetricsR\aMetrics\"\x99\x01\n" +
	"\vNodeMetrics\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Node\x18\x02 \x01(\tR\x04Node\x12\x10\n" +
	"\x03Cpu\x18\x03 \x01(\x02R\x03Cpu\x12\x16\n" +
	"\x06Memory\x18\x04 \x01(\x02R\x06Memory\x12\x12\n" +
	"\x04Disk\x18\x05 \x01(\x02R\x04Disk\x12\x16\n" +
	"\x06DiskIO\x18\x06 \x01(\x02R\x06DiskIO\x12\x10\n" +
	"\x03Url\x18\a \x01(\tR\x03Url\"A\n" +
	"\x0fJoinNodeMessage\x12\x1a\n" +
	"\bNodeType\x18\x01 \x01(\tR\bNodeType\x12\x12\n" +
	"\x04Urls\x18\x02 \x03(\tR\x04Urls\"B\n" +
	"\x10JoinNodeResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"'\n" +
	"\x11DeleteNodeMessage\x12\x12\n" +
	"\x04Urls\x18\x01 \x03(\tR\x04Urls\"D\n" +
	"\x12DeleteNodeResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg2\xab\x05\n" +
	"\vManagerLink\x12>\n" +
	"\fCheckManager\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\fApplyManager\x12\x17.cmdClient.ApplyMessage\x1a\x18.cmdClient.ApplyResponse\x12>\n" +
	"\vTaskManager\x12\x16.cmdClient.TaskMessage\x1a\x17.cmdClient.TaskResponse\x12D\n" +
	"\rCancelManager\x12\x18.cmdClient.CancelMessage\x1a\x19.cmdClient.CancelResponse\x127\n" +
	"\x04Exit\x12\x16.cmdClient.ExitMessage\x1a\x17.cmdClient.ExitResponse\x12C\n" +
	"\fDeleteTaskDb\x12\x18.cmdClient.DeleteMessage\x1a\x19.cmdClient.DeleteResponse\x12=\n" +
	"\n" +
	"ViewTaskDb\x12\x16.cmdClient.ViewMessage\x1a\x17.cmdClient.ViewResponse\x12F\n" +
	"\tCheckNode\x12\x1b.cmdClient.CheckNodeMessage\x1a\x1c.cmdClient.CheckNodeResponse\x12C\n" +
	"\bJoinNode\x12\x1a.cmdClient.JoinNodeMessage\x1a\x1b.cmdClient.JoinNodeResponse\x12I\n" +
	"\n" +
	"DeleteNode\x12\x1c.cmdClient.DeleteNodeMessage\x1a\x1d.cmdClient.DeleteNodeResponseB\x11Z\x0ftrain/cmdClientb\x06proto3"

var (
	file_cmd_cmdClient_client_proto_rawDescOnce sync.Once
	file_cmd_cmdClient_client_proto_rawDescData []byte
)

func file_cmd_cmdClient_client_proto_rawDescGZIP() []byte {
	file_cmd_cmdClient_client_proto_rawDescOnce.Do(func() {
		file_cmd_cmdClient_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_cmdClient_client_proto_rawDesc), len(file_cmd_cmdClient_client_proto_rawDesc)))
	})
	return file_cmd_cmdClient_client_proto_rawDescData
}

var file_cmd_cmdClient_client_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cmd_cmdClient_client_proto_goTypes = []any{
	(*ApplyMessage)(nil),          // 0: cmdClient.ApplyMessage
	(*ApplyResponse)(nil),         // 1: cmdClient.ApplyResponse
	(*TaskMessage)(nil),           // 2: cmdClient.TaskMessage
	(*TaskResponse)(nil),          // 3: cmdClient.TaskResponse
	(*CancelMessage)(nil),         // 4: cmdClient.CancelMessage
	(*CancelResponse)(nil),        // 5: cmdClient.CancelResponse
	(*ExitMessage)(nil),           // 6: cmdClient.ExitMessage
	(*ExitResponse)(nil),          // 7: cmdClient.ExitResponse
	(*ViewMessage)(nil),           // 8: cmdClient.ViewMessage
	(*ViewResponse)(nil),          // 9: cmdClient.ViewResponse
	(*DeleteMessage)(nil),         // 10: cmdClient.DeleteMessage
	(*DeleteResponse)(nil),        // 11: cmdClient.DeleteResponse
	(*CheckNodeMessage)(nil),      // 12: cmdClient.CheckNodeMessage
	(*CheckNodeResponse)(nil),     // 13: cmdClient.CheckNodeResponse
	(*NodeMetrics)(nil),           // 14: cmdClient.NodeMetrics
	(*JoinNodeMessage)(nil),       // 15: cmdClient.JoinNodeMessage
	(*JoinNodeResponse)(nil),      // 16: cmdClient.JoinNodeResponse
	(*DeleteNodeMessage)(nil),     // 17: cmdClient.DeleteNodeMessage
	(*DeleteNodeResponse)(nil),    // 18: cmdClient.DeleteNodeResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_cmd_cmdClient_client_proto_depIdxs = []int32{
	19, // 0: cmdClient.ViewMessage.time:type_name -> google.protobuf.Timestamp
	19, // 1: cmdClient.DeleteMessage.time:type_name -> google.protobuf.Timestamp
	14, // 2: cmdClient.CheckNodeResponse.Metrics:type_name -> cmdClient.NodeMetrics
	20, // 3: cmdClient.ManagerLink.CheckManager:input_type -> google.protobuf.Empty
	0,  // 4: cmdClient.ManagerLink.ApplyManager:input_type -> cmdClient.ApplyMessage
	2,  // 5: cmdClient.ManagerLink.TaskManager:input_type -> cmdClient.TaskMessage
	4,  // 6: cmdClient.ManagerLink.CancelManager:input_type -> cmdClient.CancelMessage
	6,  // 7: cmdClient.ManagerLink.Exit:input_type -> cmdClient.ExitMessage
	10, // 8: cmdClient.ManagerLink.DeleteTaskDb:input_type -> cmdClient.DeleteMessage
	8,  // 9: cmdClient.ManagerLink.ViewTaskDb:input_type -> cmdClient.ViewMessage
	12, // 10: cmdClient.ManagerLink.CheckNode:input_type -> cmdClient.CheckNodeMessage
	15, // 11: cmdClient.ManagerLink.JoinNode:input_type -> cmdClient.JoinNodeMessage
	17, // 12: cmdClient.ManagerLink.DeleteNode:input_type -> cmdClient.DeleteNodeMessage
	20, // 13: cmdClient.ManagerLink.CheckManager:output_type -> google.protobuf.Empty
	1,  // 14: cmdClient.ManagerLink.ApplyManager:output_type -> cmdClient.ApplyResponse
	3,  // 15: cmdClient.ManagerLink.TaskManager:output_type -> cmdClient.TaskResponse
	5,  // 16: cmdClient.ManagerLink.CancelManager:output_type -> cmdClient.CancelResponse
	7,  // 17: cmdClient.ManagerLink.Exit:output_type -> cmdClient.ExitResponse
	11, // 18: cmdClient.ManagerLink.DeleteTaskDb:output_type -> cmdClient.DeleteResponse
	9,  // 19: cmdClient.ManagerLink.ViewTaskDb:output_type -> cmdClient.ViewResponse
	13, // 20: cmdClient.ManagerLink.CheckNode:output_type -> cmdClient.CheckNodeResponse
	16, // 21: cmdClient.ManagerLink.JoinNode:output_type -> cmdClient.JoinNodeResponse
	18, // 22: cmdClient.ManagerLink.DeleteNode:output_type -> cmdClient.DeleteNodeResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cmd_cmdClient_client_proto_init() }
func file_cmd_cmdClient_client_proto_init() {
	if File_cmd_cmdClient_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_cmdClient_client_proto_rawDesc), len(file_cmd_cmdClient_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_cmdClient_client_proto_goTypes,
		DependencyIndexes: file_cmd_cmdClient_client_proto_depIdxs,
		MessageInfos:      file_cmd_cmdClient_client_proto_msgTypes,
	}.Build()
	File_cmd_cmdClient_client_proto = out.File
	file_cmd_cmdClient_client_proto_goTypes = nil
	file_cmd_cmdClient_client_proto_depIdxs = nil
}
