// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: cmd/cmdClient/client.proto

package cmdClient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMessage) Reset() {
	*x = ApplyMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMessage) ProtoMessage() {}

func (x *ApplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMessage.ProtoReflect.Descriptor instead.
func (*ApplyMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApplyMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ApplyResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMessage) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *TaskMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *TaskResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TaskResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CancelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMessage) Reset() {
	*x = CancelMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMessage) ProtoMessage() {}

func (x *CancelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMessage.ProtoReflect.Descriptor instead.
func (*CancelMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{4}
}

func (x *CancelMessage) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *CancelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CancelResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ExitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitMessage) Reset() {
	*x = ExitMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitMessage) ProtoMessage() {}

func (x *ExitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitMessage.ProtoReflect.Descriptor instead.
func (*ExitMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{6}
}

func (x *ExitMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitResponse) Reset() {
	*x = ExitResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitResponse) ProtoMessage() {}

func (x *ExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitResponse.ProtoReflect.Descriptor instead.
func (*ExitResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{7}
}

func (x *ExitResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ExitResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMessage) Reset() {
	*x = ViewMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMessage) ProtoMessage() {}

func (x *ViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMessage.ProtoReflect.Descriptor instead.
func (*ViewMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{8}
}

func (x *ViewMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ViewMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{9}
}

func (x *ViewResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ViewResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ViewResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cmd_cmdClient_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmdClient_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cmd_cmdClient_client_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *DeleteResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_cmd_cmdClient_client_proto protoreflect.FileDescriptor

const file_cmd_cmdClient_client_proto_rawDesc = "" +
	"\n" +
	"\x1acmd/cmdClient/client.proto\x12\tcmdClient\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\fApplyMessage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\rApplyResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"C\n" +
	"\vTaskMessage\x12\x10\n" +
	"\x03All\x18\x01 \x01(\bR\x03All\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"P\n" +
	"\fTaskResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"E\n" +
	"\rCancelMessage\x12\x10\n" +
	"\x03All\x18\x01 \x01(\bR\x03All\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"@\n" +
	"\x0eCancelResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"!\n" +
	"\vExitMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\fExitResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"O\n" +
	"\vViewMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"P\n" +
	"\fViewResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"Q\n" +
	"\rDeleteMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"@\n" +
	"\x0eDeleteResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg2\xd3\x03\n" +
	"\vManagerLink\x12>\n" +
	"\fCheckManager\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\fApplyManager\x12\x17.cmdClient.ApplyMessage\x1a\x18.cmdClient.ApplyResponse\x12>\n" +
	"\vTaskManager\x12\x16.cmdClient.TaskMessage\x1a\x17.cmdClient.TaskResponse\x12D\n" +
	"\rCancelManager\x12\x18.cmdClient.CancelMessage\x1a\x19.cmdClient.CancelResponse\x127\n" +
	"\x04Exit\x12\x16.cmdClient.ExitMessage\x1a\x17.cmdClient.ExitResponse\x12C\n" +
	"\fDeleteTaskDb\x12\x18.cmdClient.DeleteMessage\x1a\x19.cmdClient.DeleteResponse\x12=\n" +
	"\n" +
	"ViewTaskDb\x12\x16.cmdClient.ViewMessage\x1a\x17.cmdClient.ViewResponseB\x11Z\x0ftrain/cmdClientb\x06proto3"

var (
	file_cmd_cmdClient_client_proto_rawDescOnce sync.Once
	file_cmd_cmdClient_client_proto_rawDescData []byte
)

func file_cmd_cmdClient_client_proto_rawDescGZIP() []byte {
	file_cmd_cmdClient_client_proto_rawDescOnce.Do(func() {
		file_cmd_cmdClient_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_cmdClient_client_proto_rawDesc), len(file_cmd_cmdClient_client_proto_rawDesc)))
	})
	return file_cmd_cmdClient_client_proto_rawDescData
}

var file_cmd_cmdClient_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cmd_cmdClient_client_proto_goTypes = []any{
	(*ApplyMessage)(nil),          // 0: cmdClient.ApplyMessage
	(*ApplyResponse)(nil),         // 1: cmdClient.ApplyResponse
	(*TaskMessage)(nil),           // 2: cmdClient.TaskMessage
	(*TaskResponse)(nil),          // 3: cmdClient.TaskResponse
	(*CancelMessage)(nil),         // 4: cmdClient.CancelMessage
	(*CancelResponse)(nil),        // 5: cmdClient.CancelResponse
	(*ExitMessage)(nil),           // 6: cmdClient.ExitMessage
	(*ExitResponse)(nil),          // 7: cmdClient.ExitResponse
	(*ViewMessage)(nil),           // 8: cmdClient.ViewMessage
	(*ViewResponse)(nil),          // 9: cmdClient.ViewResponse
	(*DeleteMessage)(nil),         // 10: cmdClient.DeleteMessage
	(*DeleteResponse)(nil),        // 11: cmdClient.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_cmd_cmdClient_client_proto_depIdxs = []int32{
	12, // 0: cmdClient.ViewMessage.time:type_name -> google.protobuf.Timestamp
	12, // 1: cmdClient.DeleteMessage.time:type_name -> google.protobuf.Timestamp
	13, // 2: cmdClient.ManagerLink.CheckManager:input_type -> google.protobuf.Empty
	0,  // 3: cmdClient.ManagerLink.ApplyManager:input_type -> cmdClient.ApplyMessage
	2,  // 4: cmdClient.ManagerLink.TaskManager:input_type -> cmdClient.TaskMessage
	4,  // 5: cmdClient.ManagerLink.CancelManager:input_type -> cmdClient.CancelMessage
	6,  // 6: cmdClient.ManagerLink.Exit:input_type -> cmdClient.ExitMessage
	10, // 7: cmdClient.ManagerLink.DeleteTaskDb:input_type -> cmdClient.DeleteMessage
	8,  // 8: cmdClient.ManagerLink.ViewTaskDb:input_type -> cmdClient.ViewMessage
	13, // 9: cmdClient.ManagerLink.CheckManager:output_type -> google.protobuf.Empty
	1,  // 10: cmdClient.ManagerLink.ApplyManager:output_type -> cmdClient.ApplyResponse
	3,  // 11: cmdClient.ManagerLink.TaskManager:output_type -> cmdClient.TaskResponse
	5,  // 12: cmdClient.ManagerLink.CancelManager:output_type -> cmdClient.CancelResponse
	7,  // 13: cmdClient.ManagerLink.Exit:output_type -> cmdClient.ExitResponse
	11, // 14: cmdClient.ManagerLink.DeleteTaskDb:output_type -> cmdClient.DeleteResponse
	9,  // 15: cmdClient.ManagerLink.ViewTaskDb:output_type -> cmdClient.ViewResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_cmdClient_client_proto_init() }
func file_cmd_cmdClient_client_proto_init() {
	if File_cmd_cmdClient_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_cmdClient_client_proto_rawDesc), len(file_cmd_cmdClient_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_cmdClient_client_proto_goTypes,
		DependencyIndexes: file_cmd_cmdClient_client_proto_depIdxs,
		MessageInfos:      file_cmd_cmdClient_client_proto_msgTypes,
	}.Build()
	File_cmd_cmdClient_client_proto = out.File
	file_cmd_cmdClient_client_proto_goTypes = nil
	file_cmd_cmdClient_client_proto_depIdxs = nil
}
