// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cmd/receiveremote/receive.proto

package receive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	LogMsg        string                 `protobuf:"bytes,2,opt,name=LogMsg,proto3" json:"LogMsg,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseMsg) Reset() {
	*x = DatabaseMsg{}
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMsg) ProtoMessage() {}

func (x *DatabaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMsg.ProtoReflect.Descriptor instead.
func (*DatabaseMsg) Descriptor() ([]byte, []int) {
	return file_cmd_receiveremote_receive_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DatabaseMsg) GetLogMsg() string {
	if x != nil {
		return x.LogMsg
	}
	return ""
}

func (x *DatabaseMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DatabaseMsgRe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseMsgRe) Reset() {
	*x = DatabaseMsgRe{}
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMsgRe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMsgRe) ProtoMessage() {}

func (x *DatabaseMsgRe) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMsgRe.ProtoReflect.Descriptor instead.
func (*DatabaseMsgRe) Descriptor() ([]byte, []int) {
	return file_cmd_receiveremote_receive_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseMsgRe) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *DatabaseMsgRe) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type TrainMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	LogMsg        string                 `protobuf:"bytes,2,opt,name=LogMsg,proto3" json:"LogMsg,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainMsg) Reset() {
	*x = TrainMsg{}
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainMsg) ProtoMessage() {}

func (x *TrainMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainMsg.ProtoReflect.Descriptor instead.
func (*TrainMsg) Descriptor() ([]byte, []int) {
	return file_cmd_receiveremote_receive_proto_rawDescGZIP(), []int{2}
}

func (x *TrainMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrainMsg) GetLogMsg() string {
	if x != nil {
		return x.LogMsg
	}
	return ""
}

func (x *TrainMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TrainMsgRe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainMsgRe) Reset() {
	*x = TrainMsgRe{}
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainMsgRe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainMsgRe) ProtoMessage() {}

func (x *TrainMsgRe) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_receiveremote_receive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainMsgRe.ProtoReflect.Descriptor instead.
func (*TrainMsgRe) Descriptor() ([]byte, []int) {
	return file_cmd_receiveremote_receive_proto_rawDescGZIP(), []int{3}
}

func (x *TrainMsgRe) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *TrainMsgRe) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_cmd_receiveremote_receive_proto protoreflect.FileDescriptor

const file_cmd_receiveremote_receive_proto_rawDesc = "" +
	"\n" +
	"\x1fcmd/receiveremote/receive.proto\x12\areceive\"U\n" +
	"\vDatabaseMsg\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12\x16\n" +
	"\x06LogMsg\x18\x02 \x01(\tR\x06LogMsg\x12\x16\n" +
	"\x06TaskId\x18\x03 \x01(\tR\x06TaskId\"?\n" +
	"\rDatabaseMsgRe\x12\x12\n" +
	"\x04IsOk\x18\x01 \x01(\bR\x04IsOk\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"R\n" +
	"\bTrainMsg\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12\x16\n" +
	"\x06LogMsg\x18\x02 \x01(\tR\x06LogMsg\x12\x16\n" +
	"\x06TaskId\x18\x03 \x01(\tR\x06TaskId\"<\n" +
	"\n" +
	"TrainMsgRe\x12\x12\n" +
	"\x04IsOk\x18\x01 \x01(\bR\x04IsOk\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg2\x82\x01\n" +
	"\tRemoteLog\x12>\n" +
	"\x0eDatabaseRemote\x12\x14.receive.DatabaseMsg\x1a\x16.receive.DatabaseMsgRe\x125\n" +
	"\vTrainRemote\x12\x11.receive.TrainMsg\x1a\x13.receive.TrainMsgReB\x0fZ\rtrain/receiveb\x06proto3"

var (
	file_cmd_receiveremote_receive_proto_rawDescOnce sync.Once
	file_cmd_receiveremote_receive_proto_rawDescData []byte
)

func file_cmd_receiveremote_receive_proto_rawDescGZIP() []byte {
	file_cmd_receiveremote_receive_proto_rawDescOnce.Do(func() {
		file_cmd_receiveremote_receive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_receiveremote_receive_proto_rawDesc), len(file_cmd_receiveremote_receive_proto_rawDesc)))
	})
	return file_cmd_receiveremote_receive_proto_rawDescData
}

var file_cmd_receiveremote_receive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_receiveremote_receive_proto_goTypes = []any{
	(*DatabaseMsg)(nil),   // 0: receive.DatabaseMsg
	(*DatabaseMsgRe)(nil), // 1: receive.DatabaseMsgRe
	(*TrainMsg)(nil),      // 2: receive.TrainMsg
	(*TrainMsgRe)(nil),    // 3: receive.TrainMsgRe
}
var file_cmd_receiveremote_receive_proto_depIdxs = []int32{
	0, // 0: receive.RemoteLog.DatabaseRemote:input_type -> receive.DatabaseMsg
	2, // 1: receive.RemoteLog.TrainRemote:input_type -> receive.TrainMsg
	1, // 2: receive.RemoteLog.DatabaseRemote:output_type -> receive.DatabaseMsgRe
	3, // 3: receive.RemoteLog.TrainRemote:output_type -> receive.TrainMsgRe
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_receiveremote_receive_proto_init() }
func file_cmd_receiveremote_receive_proto_init() {
	if File_cmd_receiveremote_receive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_receiveremote_receive_proto_rawDesc), len(file_cmd_receiveremote_receive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_receiveremote_receive_proto_goTypes,
		DependencyIndexes: file_cmd_receiveremote_receive_proto_depIdxs,
		MessageInfos:      file_cmd_receiveremote_receive_proto_msgTypes,
	}.Build()
	File_cmd_receiveremote_receive_proto = out.File
	file_cmd_receiveremote_receive_proto_goTypes = nil
	file_cmd_receiveremote_receive_proto_depIdxs = nil
}
