// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: cmd/receiveremote/receive.proto

package receive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteLog_DatabaseRemote_FullMethodName = "/receive.RemoteLog/DatabaseRemote"
	RemoteLog_TrainRemote_FullMethodName    = "/receive.RemoteLog/TrainRemote"
)

// RemoteLogClient is the client API for RemoteLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteLogClient interface {
	DatabaseRemote(ctx context.Context, in *DatabaseMsg, opts ...grpc.CallOption) (*DatabaseMsgRe, error)
	TrainRemote(ctx context.Context, in *TrainMsg, opts ...grpc.CallOption) (*TrainMsgRe, error)
}

type remoteLogClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteLogClient(cc grpc.ClientConnInterface) RemoteLogClient {
	return &remoteLogClient{cc}
}

func (c *remoteLogClient) DatabaseRemote(ctx context.Context, in *DatabaseMsg, opts ...grpc.CallOption) (*DatabaseMsgRe, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseMsgRe)
	err := c.cc.Invoke(ctx, RemoteLog_DatabaseRemote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteLogClient) TrainRemote(ctx context.Context, in *TrainMsg, opts ...grpc.CallOption) (*TrainMsgRe, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainMsgRe)
	err := c.cc.Invoke(ctx, RemoteLog_TrainRemote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteLogServer is the server API for RemoteLog service.
// All implementations must embed UnimplementedRemoteLogServer
// for forward compatibility.
type RemoteLogServer interface {
	DatabaseRemote(context.Context, *DatabaseMsg) (*DatabaseMsgRe, error)
	TrainRemote(context.Context, *TrainMsg) (*TrainMsgRe, error)
	mustEmbedUnimplementedRemoteLogServer()
}

// UnimplementedRemoteLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteLogServer struct{}

func (UnimplementedRemoteLogServer) DatabaseRemote(context.Context, *DatabaseMsg) (*DatabaseMsgRe, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseRemote not implemented")
}
func (UnimplementedRemoteLogServer) TrainRemote(context.Context, *TrainMsg) (*TrainMsgRe, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainRemote not implemented")
}
func (UnimplementedRemoteLogServer) mustEmbedUnimplementedRemoteLogServer() {}
func (UnimplementedRemoteLogServer) testEmbeddedByValue()                   {}

// UnsafeRemoteLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteLogServer will
// result in compilation errors.
type UnsafeRemoteLogServer interface {
	mustEmbedUnimplementedRemoteLogServer()
}

func RegisterRemoteLogServer(s grpc.ServiceRegistrar, srv RemoteLogServer) {
	// If the following call pancis, it indicates UnimplementedRemoteLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteLog_ServiceDesc, srv)
}

func _RemoteLog_DatabaseRemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteLogServer).DatabaseRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteLog_DatabaseRemote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteLogServer).DatabaseRemote(ctx, req.(*DatabaseMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteLog_TrainRemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteLogServer).TrainRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteLog_TrainRemote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteLogServer).TrainRemote(ctx, req.(*TrainMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteLog_ServiceDesc is the grpc.ServiceDesc for RemoteLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "receive.RemoteLog",
	HandlerType: (*RemoteLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DatabaseRemote",
			Handler:    _RemoteLog_DatabaseRemote_Handler,
		},
		{
			MethodName: "TrainRemote",
			Handler:    _RemoteLog_TrainRemote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/receiveremote/receive.proto",
}
