// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: send/totrain.proto

package send

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatus) Reset() {
	*x = CheckStatus{}
	mi := &file_send_totrain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatus) ProtoMessage() {}

func (x *CheckStatus) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatus.ProtoReflect.Descriptor instead.
func (*CheckStatus) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{0}
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"` //状态是否正常
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`    //具体消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_send_totrain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CheckResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Tensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dim           []int64                `protobuf:"varint,1,rep,packed,name=Dim,proto3" json:"Dim,omitempty"`             //张量形状
	TensorContent []byte                 `protobuf:"bytes,2,opt,name=TensorContent,proto3" json:"TensorContent,omitempty"` //原始张量数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	mi := &file_send_totrain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{2}
}

func (x *Tensor) GetDim() []int64 {
	if x != nil {
		return x.Dim
	}
	return nil
}

func (x *Tensor) GetTensorContent() []byte {
	if x != nil {
		return x.TensorContent
	}
	return nil
}

type ToTrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`                                                                               //识别任务中，该数据应该被分为哪一类
	Inputs        map[string]*Tensor     `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //输出张量，若只有文本数据，则键为txt，若只有图片数据，则键为图片对应的文件后缀，若文本图片混合，则键为image的为图片Tensor，键为word的为文本Tensor
	DType         string                 `protobuf:"bytes,3,opt,name=DType,proto3" json:"DType,omitempty"`                                                                             //数据类型，若是文本则为txt，若是图片则为image，文本图片混合则为mix
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`                                                                                   //训练任务 id，标识该数据属于哪个任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToTrain) Reset() {
	*x = ToTrain{}
	mi := &file_send_totrain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToTrain) ProtoMessage() {}

func (x *ToTrain) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToTrain.ProtoReflect.Descriptor instead.
func (*ToTrain) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{3}
}

func (x *ToTrain) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToTrain) GetInputs() map[string]*Tensor {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ToTrain) GetDType() string {
	if x != nil {
		return x.DType
	}
	return ""
}

func (x *ToTrain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToTrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"` //状态是否正常
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`    //具体信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToTrainResponse) Reset() {
	*x = ToTrainResponse{}
	mi := &file_send_totrain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToTrainResponse) ProtoMessage() {}

func (x *ToTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToTrainResponse.ProtoReflect.Descriptor instead.
func (*ToTrainResponse) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{4}
}

func (x *ToTrainResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *ToTrainResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FinishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` //训练任务 id，标识哪个任务的数据已发送完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishMessage) Reset() {
	*x = FinishMessage{}
	mi := &file_send_totrain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMessage) ProtoMessage() {}

func (x *FinishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMessage.ProtoReflect.Descriptor instead.
func (*FinishMessage) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{5}
}

func (x *FinishMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`       //任务 id
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"` //错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_send_totrain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_send_totrain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_send_totrain_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ErrorMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_send_totrain_proto protoreflect.FileDescriptor

const file_send_totrain_proto_rawDesc = "" +
	"\n" +
	"\x12send/totrain.proto\x12\x04send\"\r\n" +
	"\vCheckStatus\"5\n" +
	"\rCheckResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"@\n" +
	"\x06Tensor\x12\x10\n" +
	"\x03Dim\x18\x01 \x03(\x03R\x03Dim\x12$\n" +
	"\rTensorContent\x18\x02 \x01(\fR\rTensorContent\"\xbf\x01\n" +
	"\aToTrain\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x121\n" +
	"\x06inputs\x18\x02 \x03(\v2\x19.send.ToTrain.InputsEntryR\x06inputs\x12\x14\n" +
	"\x05DType\x18\x03 \x01(\tR\x05DType\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\x1aG\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.send.TensorR\x05value:\x028\x01\"7\n" +
	"\x0fToTrainResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x1f\n" +
	"\rFinishMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"4\n" +
	"\fErrorMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error2\xdf\x01\n" +
	"\tWithTrain\x12/\n" +
	"\x05Check\x12\x11.send.CheckStatus\x1a\x13.send.CheckResponse\x121\n" +
	"\tSendTrain\x12\r.send.ToTrain\x1a\x15.send.ToTrainResponse\x124\n" +
	"\x06Finish\x12\x13.send.FinishMessage\x1a\x15.send.ToTrainResponse\x128\n" +
	"\vReportError\x12\x12.send.ErrorMessage\x1a\x15.send.ToTrainResponseB\x06Z\x04sendb\x06proto3"

var (
	file_send_totrain_proto_rawDescOnce sync.Once
	file_send_totrain_proto_rawDescData []byte
)

func file_send_totrain_proto_rawDescGZIP() []byte {
	file_send_totrain_proto_rawDescOnce.Do(func() {
		file_send_totrain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_send_totrain_proto_rawDesc), len(file_send_totrain_proto_rawDesc)))
	})
	return file_send_totrain_proto_rawDescData
}

var file_send_totrain_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_send_totrain_proto_goTypes = []any{
	(*CheckStatus)(nil),     // 0: send.CheckStatus
	(*CheckResponse)(nil),   // 1: send.CheckResponse
	(*Tensor)(nil),          // 2: send.Tensor
	(*ToTrain)(nil),         // 3: send.ToTrain
	(*ToTrainResponse)(nil), // 4: send.ToTrainResponse
	(*FinishMessage)(nil),   // 5: send.FinishMessage
	(*ErrorMessage)(nil),    // 6: send.ErrorMessage
	nil,                     // 7: send.ToTrain.InputsEntry
}
var file_send_totrain_proto_depIdxs = []int32{
	7, // 0: send.ToTrain.inputs:type_name -> send.ToTrain.InputsEntry
	2, // 1: send.ToTrain.InputsEntry.value:type_name -> send.Tensor
	0, // 2: send.WithTrain.Check:input_type -> send.CheckStatus
	3, // 3: send.WithTrain.SendTrain:input_type -> send.ToTrain
	5, // 4: send.WithTrain.Finish:input_type -> send.FinishMessage
	6, // 5: send.WithTrain.ReportError:input_type -> send.ErrorMessage
	1, // 6: send.WithTrain.Check:output_type -> send.CheckResponse
	4, // 7: send.WithTrain.SendTrain:output_type -> send.ToTrainResponse
	4, // 8: send.WithTrain.Finish:output_type -> send.ToTrainResponse
	4, // 9: send.WithTrain.ReportError:output_type -> send.ToTrainResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_send_totrain_proto_init() }
func file_send_totrain_proto_init() {
	if File_send_totrain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_send_totrain_proto_rawDesc), len(file_send_totrain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_send_totrain_proto_goTypes,
		DependencyIndexes: file_send_totrain_proto_depIdxs,
		MessageInfos:      file_send_totrain_proto_msgTypes,
	}.Build()
	File_send_totrain_proto = out.File
	file_send_totrain_proto_goTypes = nil
	file_send_totrain_proto_depIdxs = nil
}
