// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: send/totrain.proto

package send

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WithTrain_Check_FullMethodName       = "/send.WithTrain/Check"
	WithTrain_SendTrain_FullMethodName   = "/send.WithTrain/SendTrain"
	WithTrain_Finish_FullMethodName      = "/send.WithTrain/Finish"
	WithTrain_ReportError_FullMethodName = "/send.WithTrain/ReportError"
)

// WithTrainClient is the client API for WithTrain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithTrainClient interface {
	Check(ctx context.Context, in *CheckStatus, opts ...grpc.CallOption) (*CheckResponse, error)
	SendTrain(ctx context.Context, in *ToTrain, opts ...grpc.CallOption) (*ToTrainResponse, error)
	Finish(ctx context.Context, in *FinishMessage, opts ...grpc.CallOption) (*ToTrainResponse, error)
	ReportError(ctx context.Context, in *ErrorMessage, opts ...grpc.CallOption) (*ToTrainResponse, error)
}

type withTrainClient struct {
	cc grpc.ClientConnInterface
}

func NewWithTrainClient(cc grpc.ClientConnInterface) WithTrainClient {
	return &withTrainClient{cc}
}

func (c *withTrainClient) Check(ctx context.Context, in *CheckStatus, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, WithTrain_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withTrainClient) SendTrain(ctx context.Context, in *ToTrain, opts ...grpc.CallOption) (*ToTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToTrainResponse)
	err := c.cc.Invoke(ctx, WithTrain_SendTrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withTrainClient) Finish(ctx context.Context, in *FinishMessage, opts ...grpc.CallOption) (*ToTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToTrainResponse)
	err := c.cc.Invoke(ctx, WithTrain_Finish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withTrainClient) ReportError(ctx context.Context, in *ErrorMessage, opts ...grpc.CallOption) (*ToTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToTrainResponse)
	err := c.cc.Invoke(ctx, WithTrain_ReportError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithTrainServer is the server API for WithTrain service.
// All implementations must embed UnimplementedWithTrainServer
// for forward compatibility.
type WithTrainServer interface {
	Check(context.Context, *CheckStatus) (*CheckResponse, error)
	SendTrain(context.Context, *ToTrain) (*ToTrainResponse, error)
	Finish(context.Context, *FinishMessage) (*ToTrainResponse, error)
	ReportError(context.Context, *ErrorMessage) (*ToTrainResponse, error)
	mustEmbedUnimplementedWithTrainServer()
}

// UnimplementedWithTrainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWithTrainServer struct{}

func (UnimplementedWithTrainServer) Check(context.Context, *CheckStatus) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedWithTrainServer) SendTrain(context.Context, *ToTrain) (*ToTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTrain not implemented")
}
func (UnimplementedWithTrainServer) Finish(context.Context, *FinishMessage) (*ToTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finish not implemented")
}
func (UnimplementedWithTrainServer) ReportError(context.Context, *ErrorMessage) (*ToTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportError not implemented")
}
func (UnimplementedWithTrainServer) mustEmbedUnimplementedWithTrainServer() {}
func (UnimplementedWithTrainServer) testEmbeddedByValue()                   {}

// UnsafeWithTrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithTrainServer will
// result in compilation errors.
type UnsafeWithTrainServer interface {
	mustEmbedUnimplementedWithTrainServer()
}

func RegisterWithTrainServer(s grpc.ServiceRegistrar, srv WithTrainServer) {
	// If the following call pancis, it indicates UnimplementedWithTrainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WithTrain_ServiceDesc, srv)
}

func _WithTrain_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithTrainServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithTrain_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithTrainServer).Check(ctx, req.(*CheckStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithTrain_SendTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToTrain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithTrainServer).SendTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithTrain_SendTrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithTrainServer).SendTrain(ctx, req.(*ToTrain))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithTrain_Finish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithTrainServer).Finish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithTrain_Finish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithTrainServer).Finish(ctx, req.(*FinishMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithTrain_ReportError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithTrainServer).ReportError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithTrain_ReportError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithTrainServer).ReportError(ctx, req.(*ErrorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// WithTrain_ServiceDesc is the grpc.ServiceDesc for WithTrain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithTrain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "send.WithTrain",
	HandlerType: (*WithTrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _WithTrain_Check_Handler,
		},
		{
			MethodName: "SendTrain",
			Handler:    _WithTrain_SendTrain_Handler,
		},
		{
			MethodName: "Finish",
			Handler:    _WithTrain_Finish_Handler,
		},
		{
			MethodName: "ReportError",
			Handler:    _WithTrain_ReportError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "send/totrain.proto",
}
