// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: back/sender/sender.proto

package sender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Training_SendToTrain_FullMethodName    = "/sender.Training/SendToTrain"
	Training_QueryTraining_FullMethodName  = "/sender.Training/QueryTraining"
	Training_CancelTraining_FullMethodName = "/sender.Training/CancelTraining"
	Training_CheckNode_FullMethodName      = "/sender.Training/CheckNode"
)

// TrainingClient is the client API for Training service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingClient interface {
	SendToTrain(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*Response, error)
	QueryTraining(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResponse, error)
	CancelTraining(ctx context.Context, in *Cancel, opts ...grpc.CallOption) (*CancelResponse, error)
	CheckNode(ctx context.Context, in *CheckNodeRequest, opts ...grpc.CallOption) (*CheckNodeReply, error)
}

type trainingClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingClient(cc grpc.ClientConnInterface) TrainingClient {
	return &trainingClient{cc}
}

func (c *trainingClient) SendToTrain(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Training_SendToTrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) QueryTraining(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, Training_QueryTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) CancelTraining(ctx context.Context, in *Cancel, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Training_CancelTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingClient) CheckNode(ctx context.Context, in *CheckNodeRequest, opts ...grpc.CallOption) (*CheckNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNodeReply)
	err := c.cc.Invoke(ctx, Training_CheckNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingServer is the server API for Training service.
// All implementations must embed UnimplementedTrainingServer
// for forward compatibility.
type TrainingServer interface {
	SendToTrain(context.Context, *SendMessage) (*Response, error)
	QueryTraining(context.Context, *Query) (*QueryResponse, error)
	CancelTraining(context.Context, *Cancel) (*CancelResponse, error)
	CheckNode(context.Context, *CheckNodeRequest) (*CheckNodeReply, error)
	mustEmbedUnimplementedTrainingServer()
}

// UnimplementedTrainingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingServer struct{}

func (UnimplementedTrainingServer) SendToTrain(context.Context, *SendMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToTrain not implemented")
}
func (UnimplementedTrainingServer) QueryTraining(context.Context, *Query) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTraining not implemented")
}
func (UnimplementedTrainingServer) CancelTraining(context.Context, *Cancel) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTraining not implemented")
}
func (UnimplementedTrainingServer) CheckNode(context.Context, *CheckNodeRequest) (*CheckNodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNode not implemented")
}
func (UnimplementedTrainingServer) mustEmbedUnimplementedTrainingServer() {}
func (UnimplementedTrainingServer) testEmbeddedByValue()                  {}

// UnsafeTrainingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServer will
// result in compilation errors.
type UnsafeTrainingServer interface {
	mustEmbedUnimplementedTrainingServer()
}

func RegisterTrainingServer(s grpc.ServiceRegistrar, srv TrainingServer) {
	// If the following call pancis, it indicates UnimplementedTrainingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Training_ServiceDesc, srv)
}

func _Training_SendToTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).SendToTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_SendToTrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).SendToTrain(ctx, req.(*SendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_QueryTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).QueryTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_QueryTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).QueryTraining(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_CancelTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cancel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).CancelTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_CancelTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).CancelTraining(ctx, req.(*Cancel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Training_CheckNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).CheckNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Training_CheckNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).CheckNode(ctx, req.(*CheckNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Training_ServiceDesc is the grpc.ServiceDesc for Training service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Training_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sender.Training",
	HandlerType: (*TrainingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToTrain",
			Handler:    _Training_SendToTrain_Handler,
		},
		{
			MethodName: "QueryTraining",
			Handler:    _Training_QueryTraining_Handler,
		},
		{
			MethodName: "CancelTraining",
			Handler:    _Training_CancelTraining_Handler,
		},
		{
			MethodName: "CheckNode",
			Handler:    _Training_CheckNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "back/sender/sender.proto",
}
