// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: back/sender/sender.proto

package sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=IsOK,proto3" json:"IsOK,omitempty"`    //状态是否正常
	Errors        string                 `protobuf:"bytes,2,opt,name=Errors,proto3" json:"Errors,omitempty"` //错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_back_sender_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *Response) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       *SendDataset           `protobuf:"bytes,1,opt,name=Dataset,proto3" json:"Dataset,omitempty"`           //训练数据集信息
	TrainConfig   *SendTrainConfig       `protobuf:"bytes,2,opt,name=TrainConfig,proto3" json:"TrainConfig,omitempty"`   //训练配置
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                     //训练任务id
	RemoteLogURL  string                 `protobuf:"bytes,4,opt,name=RemoteLogURL,proto3" json:"RemoteLogURL,omitempty"` //训练端将会使用这个url回传外部信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_back_sender_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessage) GetDataset() *SendDataset {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *SendMessage) GetTrainConfig() *SendTrainConfig {
	if x != nil {
		return x.TrainConfig
	}
	return nil
}

func (x *SendMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMessage) GetRemoteLogURL() string {
	if x != nil {
		return x.RemoteLogURL
	}
	return ""
}

type SendDataset struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Input            string                 `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`                        //输入的数据类型，文本为txt，图片为image，文本图片混合为mix
	Validation       int32                  `protobuf:"varint,2,opt,name=Validation,proto3" json:"Validation,omitempty"`             //用于验证模型训练的数据占总训练数据的百分比，例如：该值为30%，也就是说从传输的总训练数据中抽取30%的数据用于验证训练效果
	CategoriesNumber int32                  `protobuf:"varint,3,opt,name=CategoriesNumber,proto3" json:"CategoriesNumber,omitempty"` //用于识别训练中，指明训练数据应该区分为多少类
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendDataset) Reset() {
	*x = SendDataset{}
	mi := &file_back_sender_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataset) ProtoMessage() {}

func (x *SendDataset) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataset.ProtoReflect.Descriptor instead.
func (*SendDataset) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{2}
}

func (x *SendDataset) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SendDataset) GetValidation() int32 {
	if x != nil {
		return x.Validation
	}
	return 0
}

func (x *SendDataset) GetCategoriesNumber() int32 {
	if x != nil {
		return x.CategoriesNumber
	}
	return 0
}

type SendTrainConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Epochs           int32                  `protobuf:"varint,1,opt,name=Epochs,proto3" json:"Epochs,omitempty"`                     //训练轮数
	LearningRate     float32                `protobuf:"fixed32,2,opt,name=LearningRate,proto3" json:"LearningRate,omitempty"`        //学习率
	LossFunction     string                 `protobuf:"bytes,3,opt,name=LossFunction,proto3" json:"LossFunction,omitempty"`          //损失函数的名字
	EarlyStop        bool                   `protobuf:"varint,4,opt,name=EarlyStop,proto3" json:"EarlyStop,omitempty"`               //是否采取早停策略
	EarlyStopPatient int32                  `protobuf:"varint,5,opt,name=EarlyStopPatient,proto3" json:"EarlyStopPatient,omitempty"` //早停耐心，例如：若该值为4，则意味着如果连续4轮训练损失都没有下降则停止训练
	ModelSave        string                 `protobuf:"bytes,6,opt,name=ModelSave,proto3" json:"ModelSave,omitempty"`                //模型的存储路径，注意，模型训练之后应该被存储会相同路径下
	LogSave          string                 `protobuf:"bytes,7,opt,name=LogSave,proto3" json:"LogSave,omitempty"`                    //训练端日志文件名（仅允许文件名，不允许包含目录分隔符），为空或非法时使用默认 <任务id>.txt
	TimeOut          string                 `protobuf:"bytes,8,opt,name=TimeOut,proto3" json:"TimeOut,omitempty"`                    //训练限时（d/h/m/s 组合，如 1h30m），从任务排到当前开始计时，覆盖接收数据+训练
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendTrainConfig) Reset() {
	*x = SendTrainConfig{}
	mi := &file_back_sender_sender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTrainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTrainConfig) ProtoMessage() {}

func (x *SendTrainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTrainConfig.ProtoReflect.Descriptor instead.
func (*SendTrainConfig) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{3}
}

func (x *SendTrainConfig) GetEpochs() int32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

func (x *SendTrainConfig) GetLearningRate() float32 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *SendTrainConfig) GetLossFunction() string {
	if x != nil {
		return x.LossFunction
	}
	return ""
}

func (x *SendTrainConfig) GetEarlyStop() bool {
	if x != nil {
		return x.EarlyStop
	}
	return false
}

func (x *SendTrainConfig) GetEarlyStopPatient() int32 {
	if x != nil {
		return x.EarlyStopPatient
	}
	return 0
}

func (x *SendTrainConfig) GetModelSave() string {
	if x != nil {
		return x.ModelSave
	}
	return ""
}

func (x *SendTrainConfig) GetLogSave() string {
	if x != nil {
		return x.LogSave
	}
	return ""
}

func (x *SendTrainConfig) GetTimeOut() string {
	if x != nil {
		return x.TimeOut
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_back_sender_sender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{4}
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`         //是否已经完成训练
	Epoch         int32                  `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`       //当前训练轮次，若已经训练完则填入训练结束的那个轮次
	Loss          []float32              `protobuf:"fixed32,3,rep,packed,name=loss,proto3" json:"loss,omitempty"` //每一轮次的通过损失函数计算出来的值
	IdOK          bool                   `protobuf:"varint,4,opt,name=idOK,proto3" json:"idOK,omitempty"`         //状态是否正常
	Errors        string                 `protobuf:"bytes,5,opt,name=Errors,proto3" json:"Errors,omitempty"`      //错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_back_sender_sender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *QueryResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *QueryResponse) GetLoss() []float32 {
	if x != nil {
		return x.Loss
	}
	return nil
}

func (x *QueryResponse) GetIdOK() bool {
	if x != nil {
		return x.IdOK
	}
	return false
}

func (x *QueryResponse) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_back_sender_sender_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{6}
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOK          bool                   `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`    //状态是否正常
	Errors        string                 `protobuf:"bytes,2,opt,name=Errors,proto3" json:"Errors,omitempty"` //错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_back_sender_sender_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_back_sender_sender_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_back_sender_sender_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

func (x *CancelResponse) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

var File_back_sender_sender_proto protoreflect.FileDescriptor

const file_back_sender_sender_proto_rawDesc = "" +
	"\n" +
	"\x18back/sender/sender.proto\x12\x06sender\"6\n" +
	"\bResponse\x12\x12\n" +
	"\x04IsOK\x18\x01 \x01(\bR\x04IsOK\x12\x16\n" +
	"\x06Errors\x18\x02 \x01(\tR\x06Errors\"\xab\x01\n" +
	"\vSendMessage\x12-\n" +
	"\aDataset\x18\x01 \x01(\v2\x13.sender.SendDatasetR\aDataset\x129\n" +
	"\vTrainConfig\x18\x02 \x01(\v2\x17.sender.SendTrainConfigR\vTrainConfig\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\"\n" +
	"\fRemoteLogURL\x18\x04 \x01(\tR\fRemoteLogURL\"o\n" +
	"\vSendDataset\x12\x14\n" +
	"\x05Input\x18\x01 \x01(\tR\x05Input\x12\x1e\n" +
	"\n" +
	"Validation\x18\x02 \x01(\x05R\n" +
	"Validation\x12*\n" +
	"\x10CategoriesNumber\x18\x03 \x01(\x05R\x10CategoriesNumber\"\x8d\x02\n" +
	"\x0fSendTrainConfig\x12\x16\n" +
	"\x06Epochs\x18\x01 \x01(\x05R\x06Epochs\x12\"\n" +
	"\fLearningRate\x18\x02 \x01(\x02R\fLearningRate\x12\"\n" +
	"\fLossFunction\x18\x03 \x01(\tR\fLossFunction\x12\x1c\n" +
	"\tEarlyStop\x18\x04 \x01(\bR\tEarlyStop\x12*\n" +
	"\x10EarlyStopPatient\x18\x05 \x01(\x05R\x10EarlyStopPatient\x12\x1c\n" +
	"\tModelSave\x18\x06 \x01(\tR\tModelSave\x12\x18\n" +
	"\aLogSave\x18\a \x01(\tR\aLogSave\x12\x18\n" +
	"\aTimeOut\x18\b \x01(\tR\aTimeOut\"\a\n" +
	"\x05Query\"y\n" +
	"\rQueryResponse\x12\x12\n" +
	"\x04Done\x18\x01 \x01(\bR\x04Done\x12\x14\n" +
	"\x05Epoch\x18\x02 \x01(\x05R\x05Epoch\x12\x12\n" +
	"\x04loss\x18\x03 \x03(\x02R\x04loss\x12\x12\n" +
	"\x04idOK\x18\x04 \x01(\bR\x04idOK\x12\x16\n" +
	"\x06Errors\x18\x05 \x01(\tR\x06Errors\"\b\n" +
	"\x06Cancel\"<\n" +
	"\x0eCancelResponse\x12\x12\n" +
	"\x04isOK\x18\x01 \x01(\bR\x04isOK\x12\x16\n" +
	"\x06Errors\x18\x02 \x01(\tR\x06Errors2\xb1\x01\n" +
	"\bTraining\x124\n" +
	"\vSendToTrain\x12\x13.sender.SendMessage\x1a\x10.sender.Response\x125\n" +
	"\rQueryTraining\x12\r.sender.Query\x1a\x15.sender.QueryResponse\x128\n" +
	"\x0eCancelTraining\x12\x0e.sender.Cancel\x1a\x16.sender.CancelResponseB\x0eZ\ftrain/senderb\x06proto3"

var (
	file_back_sender_sender_proto_rawDescOnce sync.Once
	file_back_sender_sender_proto_rawDescData []byte
)

func file_back_sender_sender_proto_rawDescGZIP() []byte {
	file_back_sender_sender_proto_rawDescOnce.Do(func() {
		file_back_sender_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_back_sender_sender_proto_rawDesc), len(file_back_sender_sender_proto_rawDesc)))
	})
	return file_back_sender_sender_proto_rawDescData
}

var file_back_sender_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_back_sender_sender_proto_goTypes = []any{
	(*Response)(nil),        // 0: sender.Response
	(*SendMessage)(nil),     // 1: sender.SendMessage
	(*SendDataset)(nil),     // 2: sender.SendDataset
	(*SendTrainConfig)(nil), // 3: sender.SendTrainConfig
	(*Query)(nil),           // 4: sender.Query
	(*QueryResponse)(nil),   // 5: sender.QueryResponse
	(*Cancel)(nil),          // 6: sender.Cancel
	(*CancelResponse)(nil),  // 7: sender.CancelResponse
}
var file_back_sender_sender_proto_depIdxs = []int32{
	2, // 0: sender.SendMessage.Dataset:type_name -> sender.SendDataset
	3, // 1: sender.SendMessage.TrainConfig:type_name -> sender.SendTrainConfig
	1, // 2: sender.Training.SendToTrain:input_type -> sender.SendMessage
	4, // 3: sender.Training.QueryTraining:input_type -> sender.Query
	6, // 4: sender.Training.CancelTraining:input_type -> sender.Cancel
	0, // 5: sender.Training.SendToTrain:output_type -> sender.Response
	5, // 6: sender.Training.QueryTraining:output_type -> sender.QueryResponse
	7, // 7: sender.Training.CancelTraining:output_type -> sender.CancelResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_back_sender_sender_proto_init() }
func file_back_sender_sender_proto_init() {
	if File_back_sender_sender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_back_sender_sender_proto_rawDesc), len(file_back_sender_sender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_sender_sender_proto_goTypes,
		DependencyIndexes: file_back_sender_sender_proto_depIdxs,
		MessageInfos:      file_back_sender_sender_proto_msgTypes,
	}.Build()
	File_back_sender_sender_proto = out.File
	file_back_sender_sender_proto_goTypes = nil
	file_back_sender_sender_proto_depIdxs = nil
}
