# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: receive.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'receive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreceive.proto\x12\x07receive\"=\n\x0b\x44\x61tabaseMsg\x12\x0e\n\x06Status\x18\x01 \x01(\t\x12\x0e\n\x06LogMsg\x18\x02 \x01(\t\x12\x0e\n\x06TaskId\x18\x03 \x01(\t\"/\n\rDatabaseMsgRe\x12\x0c\n\x04IsOk\x18\x01 \x01(\x08\x12\x10\n\x08\x45rrorMsg\x18\x02 \x01(\t\":\n\x08TrainMsg\x12\x0e\n\x06Status\x18\x01 \x01(\t\x12\x0e\n\x06LogMsg\x18\x02 \x01(\t\x12\x0e\n\x06TaskId\x18\x03 \x01(\t\",\n\nTrainMsgRe\x12\x0c\n\x04IsOk\x18\x01 \x01(\x08\x12\x10\n\x08\x45rrorMsg\x18\x02 \x01(\t2\x82\x01\n\tRemoteLog\x12>\n\x0e\x44\x61tabaseRemote\x12\x14.receive.DatabaseMsg\x1a\x16.receive.DatabaseMsgRe\x12\x35\n\x0bTrainRemote\x12\x11.receive.TrainMsg\x1a\x13.receive.TrainMsgReB\x0fZ\rtrain/receiveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'receive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rtrain/receive'
  _globals['_DATABASEMSG']._serialized_start=26
  _globals['_DATABASEMSG']._serialized_end=87
  _globals['_DATABASEMSGRE']._serialized_start=89
  _globals['_DATABASEMSGRE']._serialized_end=136
  _globals['_TRAINMSG']._serialized_start=138
  _globals['_TRAINMSG']._serialized_end=196
  _globals['_TRAINMSGRE']._serialized_start=198
  _globals['_TRAINMSGRE']._serialized_end=242
  _globals['_REMOTELOG']._serialized_start=245
  _globals['_REMOTELOG']._serialized_end=375
# @@protoc_insertion_point(module_scope)
