# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import receive_pb2 as receive__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in receive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteLogStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DatabaseRemote = channel.unary_unary(
                '/receive.RemoteLog/DatabaseRemote',
                request_serializer=receive__pb2.DatabaseMsg.SerializeToString,
                response_deserializer=receive__pb2.DatabaseMsgRe.FromString,
                _registered_method=True)
        self.TrainRemote = channel.unary_unary(
                '/receive.RemoteLog/TrainRemote',
                request_serializer=receive__pb2.TrainMsg.SerializeToString,
                response_deserializer=receive__pb2.TrainMsgRe.FromString,
                _registered_method=True)


class RemoteLogServicer:
    """Missing associated documentation comment in .proto file."""

    def DatabaseRemote(self, request, context):
        """数据库外部消息，训练端不需要发送
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainRemote(self, request, context):
        """训练端外部消息，数据库不需要发送
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DatabaseRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.DatabaseRemote,
                    request_deserializer=receive__pb2.DatabaseMsg.FromString,
                    response_serializer=receive__pb2.DatabaseMsgRe.SerializeToString,
            ),
            'TrainRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainRemote,
                    request_deserializer=receive__pb2.TrainMsg.FromString,
                    response_serializer=receive__pb2.TrainMsgRe.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'receive.RemoteLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('receive.RemoteLog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteLog:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DatabaseRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receive.RemoteLog/DatabaseRemote',
            receive__pb2.DatabaseMsg.SerializeToString,
            receive__pb2.DatabaseMsgRe.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/receive.RemoteLog/TrainRemote',
            receive__pb2.TrainMsg.SerializeToString,
            receive__pb2.TrainMsgRe.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
