# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sender_pb2 as sender__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sender_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendToTrain = channel.unary_unary(
                '/sender.Training/SendToTrain',
                request_serializer=sender__pb2.SendMessage.SerializeToString,
                response_deserializer=sender__pb2.Response.FromString,
                _registered_method=True)
        self.QueryTraining = channel.unary_unary(
                '/sender.Training/QueryTraining',
                request_serializer=sender__pb2.Query.SerializeToString,
                response_deserializer=sender__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.CancelTraining = channel.unary_unary(
                '/sender.Training/CancelTraining',
                request_serializer=sender__pb2.Cancel.SerializeToString,
                response_deserializer=sender__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.CheckNode = channel.unary_unary(
                '/sender.Training/CheckNode',
                request_serializer=sender__pb2.CheckNodeRequest.SerializeToString,
                response_deserializer=sender__pb2.CheckNodeReply.FromString,
                _registered_method=True)


class TrainingServicer:
    """Missing associated documentation comment in .proto file."""

    def SendToTrain(self, request, context):
        """将训练配置发送给训练端并初始化训练任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTraining(self, request, context):
        """查询训练端当前训练进度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTraining(self, request, context):
        """取消训练信号
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckNode(self, request, context):
        """查询训练端 CPU/内存/磁盘/磁盘IO 使用占比
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendToTrain': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToTrain,
                    request_deserializer=sender__pb2.SendMessage.FromString,
                    response_serializer=sender__pb2.Response.SerializeToString,
            ),
            'QueryTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTraining,
                    request_deserializer=sender__pb2.Query.FromString,
                    response_serializer=sender__pb2.QueryResponse.SerializeToString,
            ),
            'CancelTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTraining,
                    request_deserializer=sender__pb2.Cancel.FromString,
                    response_serializer=sender__pb2.CancelResponse.SerializeToString,
            ),
            'CheckNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckNode,
                    request_deserializer=sender__pb2.CheckNodeRequest.FromString,
                    response_serializer=sender__pb2.CheckNodeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sender.Training', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sender.Training', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Training:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendToTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sender.Training/SendToTrain',
            sender__pb2.SendMessage.SerializeToString,
            sender__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sender.Training/QueryTraining',
            sender__pb2.Query.SerializeToString,
            sender__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sender.Training/CancelTraining',
            sender__pb2.Cancel.SerializeToString,
            sender__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sender.Training/CheckNode',
            sender__pb2.CheckNodeRequest.SerializeToString,
            sender__pb2.CheckNodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
