# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sender.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csender.proto\x12\x06sender\"(\n\x08Response\x12\x0c\n\x04IsOK\x18\x01 \x01(\x08\x12\x0e\n\x06\x45rrors\x18\x02 \x01(\t\"\x83\x01\n\x0bSendMessage\x12$\n\x07\x44\x61taset\x18\x01 \x01(\x0b\x32\x13.sender.SendDataset\x12,\n\x0bTrainConfig\x18\x02 \x01(\x0b\x32\x17.sender.SendTrainConfig\x12\n\n\x02id\x18\x03 \x01(\t\x12\x14\n\x0cRemoteLogUrl\x18\x04 \x01(\t\"J\n\x0bSendDataset\x12\r\n\x05Input\x18\x01 \x01(\t\x12\x12\n\nValidation\x18\x02 \x01(\x05\x12\x18\n\x10\x43\x61tegoriesNumber\x18\x03 \x01(\x05\"\xaf\x01\n\x0fSendTrainConfig\x12\x0e\n\x06\x45pochs\x18\x01 \x01(\x05\x12\x14\n\x0cLearningRate\x18\x02 \x01(\x02\x12\x14\n\x0cLossFunction\x18\x03 \x01(\t\x12\x11\n\tEarlyStop\x18\x04 \x01(\x08\x12\x18\n\x10\x45\x61rlyStopPatient\x18\x05 \x01(\x05\x12\x11\n\tModelSave\x18\x06 \x01(\t\x12\x0f\n\x07LogSave\x18\x07 \x01(\t\x12\x0f\n\x07TimeOut\x18\x08 \x01(\t\"\x07\n\x05Query\"X\n\rQueryResponse\x12\x0c\n\x04\x44one\x18\x01 \x01(\x08\x12\r\n\x05\x45poch\x18\x02 \x01(\x05\x12\x0c\n\x04loss\x18\x03 \x03(\x02\x12\x0c\n\x04idOK\x18\x04 \x01(\x08\x12\x0e\n\x06\x45rrors\x18\x05 \x01(\t\"\x08\n\x06\x43\x61ncel\".\n\x0e\x43\x61ncelResponse\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\x12\x0e\n\x06\x45rrors\x18\x02 \x01(\t\"\x12\n\x10\x43heckNodeRequest\"K\n\x0e\x43heckNodeReply\x12\x0b\n\x03\x43pu\x18\x01 \x01(\x02\x12\x0e\n\x06Memory\x18\x02 \x01(\x02\x12\x0c\n\x04\x44isk\x18\x03 \x01(\x02\x12\x0e\n\x06\x44iskIO\x18\x04 \x01(\x02\x32\xf0\x01\n\x08Training\x12\x34\n\x0bSendToTrain\x12\x13.sender.SendMessage\x1a\x10.sender.Response\x12\x35\n\rQueryTraining\x12\r.sender.Query\x1a\x15.sender.QueryResponse\x12\x38\n\x0e\x43\x61ncelTraining\x12\x0e.sender.Cancel\x1a\x16.sender.CancelResponse\x12=\n\tCheckNode\x12\x18.sender.CheckNodeRequest\x1a\x16.sender.CheckNodeReplyB\x0eZ\x0ctrain/senderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014train/sender'
  _globals['_RESPONSE']._serialized_start=24
  _globals['_RESPONSE']._serialized_end=64
  _globals['_SENDMESSAGE']._serialized_start=67
  _globals['_SENDMESSAGE']._serialized_end=198
  _globals['_SENDDATASET']._serialized_start=200
  _globals['_SENDDATASET']._serialized_end=274
  _globals['_SENDTRAINCONFIG']._serialized_start=277
  _globals['_SENDTRAINCONFIG']._serialized_end=452
  _globals['_QUERY']._serialized_start=454
  _globals['_QUERY']._serialized_end=461
  _globals['_QUERYRESPONSE']._serialized_start=463
  _globals['_QUERYRESPONSE']._serialized_end=551
  _globals['_CANCEL']._serialized_start=553
  _globals['_CANCEL']._serialized_end=561
  _globals['_CANCELRESPONSE']._serialized_start=563
  _globals['_CANCELRESPONSE']._serialized_end=609
  _globals['_CHECKNODEREQUEST']._serialized_start=611
  _globals['_CHECKNODEREQUEST']._serialized_end=629
  _globals['_CHECKNODEREPLY']._serialized_start=631
  _globals['_CHECKNODEREPLY']._serialized_end=706
  _globals['_TRAINING']._serialized_start=709
  _globals['_TRAINING']._serialized_end=949
# @@protoc_insertion_point(module_scope)
