# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import totrain_pb2 as totrain__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in totrain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WithTrainStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/send.WithTrain/Check',
                request_serializer=totrain__pb2.CheckStatus.SerializeToString,
                response_deserializer=totrain__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.SendTrain = channel.unary_unary(
                '/send.WithTrain/SendTrain',
                request_serializer=totrain__pb2.ToTrain.SerializeToString,
                response_deserializer=totrain__pb2.ToTrainResponse.FromString,
                _registered_method=True)
        self.Finish = channel.unary_unary(
                '/send.WithTrain/Finish',
                request_serializer=totrain__pb2.FinishMessage.SerializeToString,
                response_deserializer=totrain__pb2.ToTrainResponse.FromString,
                _registered_method=True)
        self.ReportError = channel.unary_unary(
                '/send.WithTrain/ReportError',
                request_serializer=totrain__pb2.ErrorMessage.SerializeToString,
                response_deserializer=totrain__pb2.ToTrainResponse.FromString,
                _registered_method=True)


class WithTrainServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """检查训练段是否存活
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTrain(self, request, context):
        """将预处理好的数据发送给训练端
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finish(self, request, context):
        """通知训练端：某任务数据已全部发送完毕
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportError(self, request, context):
        """数据端通知训练端：预处理出错
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WithTrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=totrain__pb2.CheckStatus.FromString,
                    response_serializer=totrain__pb2.CheckResponse.SerializeToString,
            ),
            'SendTrain': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTrain,
                    request_deserializer=totrain__pb2.ToTrain.FromString,
                    response_serializer=totrain__pb2.ToTrainResponse.SerializeToString,
            ),
            'Finish': grpc.unary_unary_rpc_method_handler(
                    servicer.Finish,
                    request_deserializer=totrain__pb2.FinishMessage.FromString,
                    response_serializer=totrain__pb2.ToTrainResponse.SerializeToString,
            ),
            'ReportError': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportError,
                    request_deserializer=totrain__pb2.ErrorMessage.FromString,
                    response_serializer=totrain__pb2.ToTrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'send.WithTrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('send.WithTrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WithTrain:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/send.WithTrain/Check',
            totrain__pb2.CheckStatus.SerializeToString,
            totrain__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/send.WithTrain/SendTrain',
            totrain__pb2.ToTrain.SerializeToString,
            totrain__pb2.ToTrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/send.WithTrain/Finish',
            totrain__pb2.FinishMessage.SerializeToString,
            totrain__pb2.ToTrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/send.WithTrain/ReportError',
            totrain__pb2.ErrorMessage.SerializeToString,
            totrain__pb2.ToTrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
