# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: totrain.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'totrain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtotrain.proto\x12\x04send\"\r\n\x0b\x43heckStatus\"*\n\rCheckResponse\x12\x0c\n\x04IsOK\x18\x01 \x01(\x08\x12\x0b\n\x03Msg\x18\x02 \x01(\t\",\n\x06Tensor\x12\x0b\n\x03\x44im\x18\x01 \x03(\x03\x12\x15\n\rTensorContent\x18\x02 \x01(\x0c\"\x9a\x01\n\x07ToTrain\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12)\n\x06inputs\x18\x02 \x03(\x0b\x32\x19.send.ToTrain.InputsEntry\x12\r\n\x05\x44Type\x18\x03 \x01(\t\x12\n\n\x02Id\x18\x04 \x01(\t\x1a;\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.send.Tensor:\x02\x38\x01\",\n\x0fToTrainResponse\x12\x0c\n\x04IsOK\x18\x01 \x01(\x08\x12\x0b\n\x03Msg\x18\x02 \x01(\t\"\x1b\n\rFinishMessage\x12\n\n\x02Id\x18\x01 \x01(\t\")\n\x0c\x45rrorMessage\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05\x45rror\x18\x02 \x01(\t2\xdf\x01\n\tWithTrain\x12/\n\x05\x43heck\x12\x11.send.CheckStatus\x1a\x13.send.CheckResponse\x12\x31\n\tSendTrain\x12\r.send.ToTrain\x1a\x15.send.ToTrainResponse\x12\x34\n\x06\x46inish\x12\x13.send.FinishMessage\x1a\x15.send.ToTrainResponse\x12\x38\n\x0bReportError\x12\x12.send.ErrorMessage\x1a\x15.send.ToTrainResponseB\x06Z\x04sendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'totrain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004send'
  _globals['_TOTRAIN_INPUTSENTRY']._loaded_options = None
  _globals['_TOTRAIN_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_CHECKSTATUS']._serialized_start=23
  _globals['_CHECKSTATUS']._serialized_end=36
  _globals['_CHECKRESPONSE']._serialized_start=38
  _globals['_CHECKRESPONSE']._serialized_end=80
  _globals['_TENSOR']._serialized_start=82
  _globals['_TENSOR']._serialized_end=126
  _globals['_TOTRAIN']._serialized_start=129
  _globals['_TOTRAIN']._serialized_end=283
  _globals['_TOTRAIN_INPUTSENTRY']._serialized_start=224
  _globals['_TOTRAIN_INPUTSENTRY']._serialized_end=283
  _globals['_TOTRAINRESPONSE']._serialized_start=285
  _globals['_TOTRAINRESPONSE']._serialized_end=329
  _globals['_FINISHMESSAGE']._serialized_start=331
  _globals['_FINISHMESSAGE']._serialized_end=358
  _globals['_ERRORMESSAGE']._serialized_start=360
  _globals['_ERRORMESSAGE']._serialized_end=401
  _globals['_WITHTRAIN']._serialized_start=404
  _globals['_WITHTRAIN']._serialized_end=627
# @@protoc_insertion_point(module_scope)
