// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: back/server/client.proto

package cmdClient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerLink_CheckManager_FullMethodName  = "/cmdClient.ManagerLink/CheckManager"
	ManagerLink_ApplyManager_FullMethodName  = "/cmdClient.ManagerLink/ApplyManager"
	ManagerLink_TaskManager_FullMethodName   = "/cmdClient.ManagerLink/TaskManager"
	ManagerLink_CancelManager_FullMethodName = "/cmdClient.ManagerLink/CancelManager"
	ManagerLink_Exit_FullMethodName          = "/cmdClient.ManagerLink/Exit"
	ManagerLink_DeleteTaskDb_FullMethodName  = "/cmdClient.ManagerLink/DeleteTaskDb"
	ManagerLink_ViewTaskDb_FullMethodName    = "/cmdClient.ManagerLink/ViewTaskDb"
	ManagerLink_CheckNode_FullMethodName     = "/cmdClient.ManagerLink/CheckNode"
	ManagerLink_JoinNode_FullMethodName      = "/cmdClient.ManagerLink/JoinNode"
	ManagerLink_DeleteNode_FullMethodName    = "/cmdClient.ManagerLink/DeleteNode"
)

// ManagerLinkClient is the client API for ManagerLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerLinkClient interface {
	CheckManager(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ApplyManager(ctx context.Context, in *ApplyMessage, opts ...grpc.CallOption) (*ApplyResponse, error)
	TaskManager(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskResponse, error)
	CancelManager(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error)
	Exit(ctx context.Context, in *ExitMessage, opts ...grpc.CallOption) (*ExitResponse, error)
	DeleteTaskDb(ctx context.Context, in *DeleteMessage, opts ...grpc.CallOption) (*DeleteResponse, error)
	ViewTaskDb(ctx context.Context, in *ViewMessage, opts ...grpc.CallOption) (*ViewResponse, error)
	CheckNode(ctx context.Context, in *CheckNodeMessage, opts ...grpc.CallOption) (*CheckNodeResponse, error)
	JoinNode(ctx context.Context, in *JoinNodeMessage, opts ...grpc.CallOption) (*JoinNodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeMessage, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
}

type managerLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerLinkClient(cc grpc.ClientConnInterface) ManagerLinkClient {
	return &managerLinkClient{cc}
}

func (c *managerLinkClient) CheckManager(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagerLink_CheckManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) ApplyManager(ctx context.Context, in *ApplyMessage, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, ManagerLink_ApplyManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) TaskManager(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, ManagerLink_TaskManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) CancelManager(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, ManagerLink_CancelManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) Exit(ctx context.Context, in *ExitMessage, opts ...grpc.CallOption) (*ExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitResponse)
	err := c.cc.Invoke(ctx, ManagerLink_Exit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) DeleteTaskDb(ctx context.Context, in *DeleteMessage, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ManagerLink_DeleteTaskDb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) ViewTaskDb(ctx context.Context, in *ViewMessage, opts ...grpc.CallOption) (*ViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, ManagerLink_ViewTaskDb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) CheckNode(ctx context.Context, in *CheckNodeMessage, opts ...grpc.CallOption) (*CheckNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNodeResponse)
	err := c.cc.Invoke(ctx, ManagerLink_CheckNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) JoinNode(ctx context.Context, in *JoinNodeMessage, opts ...grpc.CallOption) (*JoinNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinNodeResponse)
	err := c.cc.Invoke(ctx, ManagerLink_JoinNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerLinkClient) DeleteNode(ctx context.Context, in *DeleteNodeMessage, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, ManagerLink_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerLinkServer is the server API for ManagerLink service.
// All implementations must embed UnimplementedManagerLinkServer
// for forward compatibility.
type ManagerLinkServer interface {
	CheckManager(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ApplyManager(context.Context, *ApplyMessage) (*ApplyResponse, error)
	TaskManager(context.Context, *TaskMessage) (*TaskResponse, error)
	CancelManager(context.Context, *CancelMessage) (*CancelResponse, error)
	Exit(context.Context, *ExitMessage) (*ExitResponse, error)
	DeleteTaskDb(context.Context, *DeleteMessage) (*DeleteResponse, error)
	ViewTaskDb(context.Context, *ViewMessage) (*ViewResponse, error)
	CheckNode(context.Context, *CheckNodeMessage) (*CheckNodeResponse, error)
	JoinNode(context.Context, *JoinNodeMessage) (*JoinNodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeMessage) (*DeleteNodeResponse, error)
	mustEmbedUnimplementedManagerLinkServer()
}

// UnimplementedManagerLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerLinkServer struct{}

func (UnimplementedManagerLinkServer) CheckManager(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckManager not implemented")
}
func (UnimplementedManagerLinkServer) ApplyManager(context.Context, *ApplyMessage) (*ApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyManager not implemented")
}
func (UnimplementedManagerLinkServer) TaskManager(context.Context, *TaskMessage) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskManager not implemented")
}
func (UnimplementedManagerLinkServer) CancelManager(context.Context, *CancelMessage) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelManager not implemented")
}
func (UnimplementedManagerLinkServer) Exit(context.Context, *ExitMessage) (*ExitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedManagerLinkServer) DeleteTaskDb(context.Context, *DeleteMessage) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaskDb not implemented")
}
func (UnimplementedManagerLinkServer) ViewTaskDb(context.Context, *ViewMessage) (*ViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewTaskDb not implemented")
}
func (UnimplementedManagerLinkServer) CheckNode(context.Context, *CheckNodeMessage) (*CheckNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNode not implemented")
}
func (UnimplementedManagerLinkServer) JoinNode(context.Context, *JoinNodeMessage) (*JoinNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinNode not implemented")
}
func (UnimplementedManagerLinkServer) DeleteNode(context.Context, *DeleteNodeMessage) (*DeleteNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedManagerLinkServer) mustEmbedUnimplementedManagerLinkServer() {}
func (UnimplementedManagerLinkServer) testEmbeddedByValue()                     {}

// UnsafeManagerLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerLinkServer will
// result in compilation errors.
type UnsafeManagerLinkServer interface {
	mustEmbedUnimplementedManagerLinkServer()
}

func RegisterManagerLinkServer(s grpc.ServiceRegistrar, srv ManagerLinkServer) {
	// If the following call pancis, it indicates UnimplementedManagerLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerLink_ServiceDesc, srv)
}

func _ManagerLink_CheckManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).CheckManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_CheckManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).CheckManager(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_ApplyManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).ApplyManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_ApplyManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).ApplyManager(ctx, req.(*ApplyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_TaskManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).TaskManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_TaskManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).TaskManager(ctx, req.(*TaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_CancelManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).CancelManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_CancelManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).CancelManager(ctx, req.(*CancelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_Exit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).Exit(ctx, req.(*ExitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_DeleteTaskDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).DeleteTaskDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_DeleteTaskDb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).DeleteTaskDb(ctx, req.(*DeleteMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_ViewTaskDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).ViewTaskDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_ViewTaskDb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).ViewTaskDb(ctx, req.(*ViewMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_CheckNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).CheckNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_CheckNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).CheckNode(ctx, req.(*CheckNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_JoinNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).JoinNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_JoinNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).JoinNode(ctx, req.(*JoinNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerLink_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerLinkServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerLink_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerLinkServer).DeleteNode(ctx, req.(*DeleteNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerLink_ServiceDesc is the grpc.ServiceDesc for ManagerLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdClient.ManagerLink",
	HandlerType: (*ManagerLinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckManager",
			Handler:    _ManagerLink_CheckManager_Handler,
		},
		{
			MethodName: "ApplyManager",
			Handler:    _ManagerLink_ApplyManager_Handler,
		},
		{
			MethodName: "TaskManager",
			Handler:    _ManagerLink_TaskManager_Handler,
		},
		{
			MethodName: "CancelManager",
			Handler:    _ManagerLink_CancelManager_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _ManagerLink_Exit_Handler,
		},
		{
			MethodName: "DeleteTaskDb",
			Handler:    _ManagerLink_DeleteTaskDb_Handler,
		},
		{
			MethodName: "ViewTaskDb",
			Handler:    _ManagerLink_ViewTaskDb_Handler,
		},
		{
			MethodName: "CheckNode",
			Handler:    _ManagerLink_CheckNode_Handler,
		},
		{
			MethodName: "JoinNode",
			Handler:    _ManagerLink_JoinNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _ManagerLink_DeleteNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "back/server/client.proto",
}
